import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from './components/header/Header';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`antialiased min-h-screen flex flex-col relative`}>
				<header className="fixed top-0 z-50 w-full">
					<Header />
				</header>
				{children}
			</body>
		</html>
	);
}
